M48
; DRILL file {KiCad (6.0.0)} date Tue Jan  4 00:39:45 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-04T00:39:45-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X112.268Y-76.124
X112.268Y-102.108
X135.89Y-76.124
X135.89Y-102.108
T0
M30
