M48
; DRILL file {KiCad (6.0.0)} date Thu Aug 18 21:48:34 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-18T21:48:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.050
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X110.0Y-44.013
X144.0Y-44.013
T2
X94.996Y-34.036
X94.996Y-77.724
X159.004Y-34.036
X159.004Y-77.724
T0
M30
